var GlideSession = Class.create();
GlideSession.prototype = {
	
	/**
	 * Impersonate a user for the duration of the session (INCLUDING AFTER THE SCRIPT IS FINISHED RUNNING!), or until the onlineImpersonate() method is called again, with another (or the original user's) user_id.
	 * @param userID {string} The user_id OR the sys_id of the user you'd like to impersonate for this session (e.g. 'admin' or '6816f79cc0a8016401c5a33be04be441').
	 * @return The sys_id of the CURRENT user (PRE-impersonation). This can later be passed into session.onlineImpersonate() in order to reimpersonate the original session, which prevents ending up stuck in the other user's session after the script is finished running.
	 * @example
	 * var originalUserID = session.onlineImpersonate('abel_tuter');
	 * //script here, executes as the impersonated user
	 * session.onlineImpersonate(originalUser);
	 */
	onlineImpersonate: function(userID) {
		return 'abc123';
	},
	
	getCacheFlush: function() {},
	stack: {},
	setClientIP: function() {},
	getStacks: function() {},
	dateFormat: {},
	setStrictQuery: function() {},
	getTimeFormat: function() {},
	isAllowedToBeMaint: function() {},
	sessionID: {},
	addUniqueAdminLevelErrorMessage: function() {},
	setRedirect: function() {},
	setSessionID: function() {},
	getStackName: function() {},
	clientDataMap: {},
	merge: function() {},
	clientIP: {},
	setCacheFlush: function() {},
	rememberHeldMutex: function() {},
	getFullName: function() {},
	setTimeFormat: function() {},
	getRoles: function() {},
	clearCategoryParms: function() {},
	setDomainEnabled: function() {},
	getOpticsContext: function() {},
	jsFunction_setContextualMode: function() {},
	timeZone: {},
	getLastUser: function() {},
	addAdminLevelErrorMessage: function() {},
	UID: {},
	getLicenses: function() {},
	jsFunction_getContextualMode: function() {},
	onlineUnimpersonate: function() {},
	loggedIn: '',
	addUniqueMessage: function() {},
	workflowDisabled: '',
	setHttpSession: function() {},
	getClientIP: function() {},
	renameStack: function() {},
	businessRuleStack: {},
	flushEncryptionContext: function() {},
	setWatchField: function() {},
	stackParm: '',
	loginHome: '',
	getImageCache: function() {},
	alreadyGettingUserInThisSession: '',
	addInfoMessage: function() {},
	ignoredCreateElement: '',
	toString: function() {},
	resetURI: function() {},
	clearSessionProperties: function() {},
	setDomainID: function() {},
	isInteractive: function() {},
	currentApplicationIdWithoutUpdateSet: '',
	refreshNavigator: '',
	language: {},
	hasNamedMessages: function() {},
	getBooleanProperty: function() {},
	addMessage: function() {},
	getNamedMessages: function() {},
	getSessionKey: function() {},
	getStackParms: function() {},
	getUID: function() {},
	activatedElevatedRoles: {},
	separation: '',
	setIsEdgeEncrypted: function() {},
	getImpersonatingUserDisplayName: function() {},
	isTextIndexSuppressed: function() {},
	getMessageTypes: function() {},
	getTrackMetadataDeletes: function() {},
	getAvailableElevatedRoles: function() {},
	isImpersonatingUserAdmin: function() {},
	valueBound: function() {},
	setReturn: function() {},
	setNavMessage: function() {},
	getHttpSession: function() {},
	isEdgeEncryptedSession: function() {},
	isDeveloper: function() {},
	timeZoneName: {},
	flushMessages: function() {},
	addUniqueErrorMessage: function() {},
	isLoggedIn: function() {},
	setCacheIgnoreFlushTable: function() {},
	getDateFormat: function() {},
	getCacheIgnoreFlushTable: function() {},
	getTransactionApplicationId: function() {},
	getEncryptionContext: function() {},
	encryptionContext: {},
	isLockedOut: function() {},
	getInfoMessages: function() {},
	releaseConnection: function() {},
	getWorkflow: function() {},
	getRedirect: function() {},
	setIgnoredCreateElement: function() {},
	rotatingSession: '',
	notifyAll: function() {},
	roles: {},
	getStackObject: function() {},
	setCurrentApplicationId: function() {},
	getCurrentDomain: function() {},
	isIgnoredCreateElement: function() {},
	isUpdateSynchSuppressed: function() {},
	hashCode: function() {},
	getLanguageNoLookup: function() {},
	getCategoryParm: function() {},
	stackParms: '',
	addUniqueInfoMessage: function() {},
	currentDomainID: {},
	addTrivialMessage: function() {},
	getSessionID: function() {},
	setDateFormat: function() {},
	setWorkflowDisabled: function() {},
	sessionKey: {},
	getOriginatingUserName: function() {},
	fullName: {},
	getBrowserLocale: function() {},
	userName: {},
	setWorkflow: function() {},
	setStackParm: function() {},
	setStack: function() {},
	getNavMessage: function() {},
	getBusinessRuleStack: function() {},
	setSuppressTextIndexWhenSessionWorkflowOff: function() {},
	suppressTextIndex: function() {},
	categoryParms: '',
	clearActiveDBs: function() {},
	setInteractive: function() {},
	interactive: '',
	setAlreadyGettingUserInThisSession: function() {},
	booleanProperty: '',
	addNotification: function() {},
	property: '',
	isSuppressTextIndexWhenSessionWorkflowOff: function() {},
	separationEnabled: function() {},
	getErrorMessages: function() {},
	setUser: function() {},
	getStrictQuery: function() {},
	checkActiveDBs: function() {},
	getClientDataMap: function() {},
	putClientData: function() {},
	setTrackMetadataDeletes: function() {},
	suppressUpdateSynch: function() {},
	clearWatchField: function() {},
	cloneSessionProperties: function() {},
	setCategoryParm: function() {},
	setRefreshNavigator: function() {},
	runEngines: '',
	lockedOut: '',
	getCurrentApplicationScope: function() {},
	stackObject: '',
	wait: function() {},
	getReturn: function() {},
	getCategoryParms: function() {},
	getCurrentDomainID: function() {},
	setRotatingSession: function() {},
	putProperty: function() {},
	URI: {},
	notify: function() {},
	getTimeZoneName: function() {},
	getImpersonatingUserName: function() {},
	getDateTimeFormat: function() {},
	addErrorMessage: function() {},
	getRecordCacheSize: function() {},
	isOwnedByOtherThread: function() {},
	availableElevatedRoles: {},
	getLanguage: function() {},
	holdsMutex: function() {},
	getSessionWrites: function() {},
	categoryParm: '',
	setSeparation: function() {},
	getIntProperty: function() {},
	setCurrentApplicationIdWithoutUpdateSet: function() {},
	equals: function() {},
	getTrivialMessages: function() {},
	getClass: function() {},
	clearOpticsContext: function() {},
	establishSession: function() {},
	getAccessMessages: function() {},
	getContextualMode: function() {},
	getTimeZone: function() {},
	getWatchField: function() {},
	clearClientData: function() {},
	isEdgeEncrypted: '',
	getTimeZoneShortName: function() {},
	setRecordCacheSize: function() {},
	actualUserIsAdmin: function() {},
	getCurrentApplicationId: function() {},
	impersonateWithDefault: function() {},
	domainID: '',
	clearProperty: function() {},
	timeZoneShortName: {},
	impersonate: function() {},
	setLastUser: function() {},
	getUserName: function() {},
	workflow: '',
	namedMessages: '',
	setURI: function() {},
	setRunEngines: function() {},
	clearCategoryParm: function() {},
	enableDomain: function() {},
	isImpersonating: function() {},
	isImpersonatingUserReadOnly: function() {},
	getStackParm: function() {},
	valueUnbound: function() {},
	connectionStatus: function() {},
	hasRole: function() {},
	loadUserByID: function() {},
	clientData: '',
	setBrowserLocale: function() {},
	setIsAllowedToBeMaint: function() {},
	getURI: function() {},
	setLanguage: function() {},
	getRunEngines: function() {},
	getUserDisplayName: function() {},
	startTransaction: function() {},
	getDomainEnabled: function() {},
	getUser: function() {},
	setAuthedForTimeLimitedCredentials: function() {},
	stackName: {},
	setLoggedIn: function() {},
	watchField: {},
	httpSession: {},
	dateTimeFormat: {},
	getBusinessRuleExceptionHandler: function() {},
	getLoginHome: function() {},
	hasDBs: function() {},
	intProperty: '',
	getProperty: function() {},
	getClientData: function() {},
	setBusinessRuleExceptionHandler: function() {},
	forgetHeldMutex: function() {},
	getActivatedElevatedRoles: function() {},
	clearBusinessRuleStack: function() {},
	setTimeZoneName: function() {},
	isAuthedForTimeLimitedCredentials: function() {},
	timeFormat: {},
	getStack: function() {},
	user: {}
};

var session = new GlideSession();